# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSegmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('desc', models.CharField(max_length=150)),
                ('namespace', models.CharField(max_length=100, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_modified', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomSegmentTypeSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=150)),
                ('namespace', models.CharField(max_length=100, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocal.CustomSegmentType')),
            ],
        ),
        migrations.CreateModel(
            name='ExporterSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_path', models.CharField(max_length=150)),
                ('export_git_path', models.CharField(default='', max_length=150)),
                ('game_config_export_path', models.CharField(default='', max_length=150)),
                ('game_config_name', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=150)),
                ('namespace', models.CharField(max_length=100, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('namespace', models.CharField(max_length=150, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_exporting', models.BooleanField(default=False)),
                ('is_modified', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=150, unique=True)),
                ('status', models.IntegerField(choices=[(1, 'Prepare'), (2, 'Successfully'), (3, 'Failed')], default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocal.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Protocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=150)),
                ('route', models.CharField(blank=True, default='', max_length=100)),
                ('namespace', models.CharField(max_length=100, unique=True)),
                ('protocal_id', models.IntegerField()),
                ('protocal_unique_id', models.IntegerField(unique=True)),
                ('is_modified', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocal.Module')),
                ('relate_protocal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protocal.Protocal')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocal.ProtocalType')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=150)),
                ('namespace', models.CharField(max_length=100, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SegmentProtoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SegmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('desc', models.CharField(max_length=150)),
                ('is_basic', models.BooleanField(default=True)),
                ('show_priority', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='protocal.Project')),
            ],
        ),
        migrations.AddField(
            model_name='segment',
            name='extra_type1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segment_extra_type_1', to='protocal.SegmentType'),
        ),
        migrations.AddField(
            model_name='segment',
            name='extra_type2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segment_extra_type_2', to='protocal.SegmentType'),
        ),
        migrations.AddField(
            model_name='segment',
            name='protocal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocal.Protocal'),
        ),
        migrations.AddField(
            model_name='segment',
            name='protocal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocal.SegmentProtoType'),
        ),
        migrations.AddField(
            model_name='segment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocal.SegmentType'),
        ),
        migrations.AddField(
            model_name='module',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocal.Project'),
        ),
        migrations.AddField(
            model_name='customsegmenttypesegment',
            name='extra_type1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_type_segment_extra_type_1', to='protocal.SegmentType'),
        ),
        migrations.AddField(
            model_name='customsegmenttypesegment',
            name='extra_type2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_type_segment_extra_type_2', to='protocal.SegmentType'),
        ),
        migrations.AddField(
            model_name='customsegmenttypesegment',
            name='protocal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocal.SegmentProtoType'),
        ),
        migrations.AddField(
            model_name='customsegmenttypesegment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocal.SegmentType'),
        ),
        migrations.AddField(
            model_name='customsegmenttype',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='protocal.SegmentType'),
        ),
    ]
