# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=150)),
                ('namespace', models.CharField(max_length=100, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocal.Protocal')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocal.Module')),
                ('type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='protocal.SegmentType')),
            ],
        ),
        migrations.CreateModel(
            name='CustomTypeSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocal.CustomType')),
                ('protocal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocal.SegmentProtoType')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocal.SegmentType')),
            ],
        ),
    ]
