# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocal', '0002_customtype_customtypesegment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segmenttype',
            name='module',
        ),
    ]
