# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocal', '0002_auto_20170728_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocal',
            name='route',
        ),
    ]
