# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocal', '0003_remove_protocal_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customsegmenttype',
            name='type',
        ),
        migrations.RemoveField(
            model_name='customsegmenttypesegment',
            name='belong',
        ),
        migrations.RemoveField(
            model_name='customsegmenttypesegment',
            name='extra_type1',
        ),
        migrations.RemoveField(
            model_name='customsegmenttypesegment',
            name='extra_type2',
        ),
        migrations.RemoveField(
            model_name='customsegmenttypesegment',
            name='protocal_type',
        ),
        migrations.RemoveField(
            model_name='customsegmenttypesegment',
            name='type',
        ),
        migrations.RemoveField(
            model_name='exportersetting',
            name='export_git_path',
        ),
        migrations.RemoveField(
            model_name='exportersetting',
            name='game_config_export_path',
        ),
        migrations.RemoveField(
            model_name='exportersetting',
            name='game_config_name',
        ),
        migrations.DeleteModel(
            name='CustomSegmentType',
        ),
        migrations.DeleteModel(
            name='CustomSegmentTypeSegment',
        ),
    ]
