# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocal', '0003_remove_segmenttype_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmenttype',
            name='module',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='protocal.Module'),
        ),
    ]
