# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocal', '0004_segmenttype_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enum',
            name='belong',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='protocal.Protocal'),
        ),
    ]
