# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocal', '0007_auto_20170802_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmenttype',
            name='provider_type',
            field=models.IntegerField(default=0),
        ),
    ]
