# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocal', '0008_segmenttype_provider_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtypesegment',
            name='defaultEnum',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='protocal.EnmuSegment'),
        ),
        migrations.AddField(
            model_name='segment',
            name='defaultEnum',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='protocal.EnmuSegment'),
        ),
        migrations.AlterField(
            model_name='customtype',
            name='module',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='protocal.Module'),
        ),
        migrations.AlterField(
            model_name='enum',
            name='module',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='protocal.Module'),
        ),
        migrations.AlterField(
            model_name='protocal',
            name='module',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='protocal.Module'),
        ),
    ]
