# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocal', '0009_auto_20170803_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtype',
            name='belong_ct',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='protocal.CustomType'),
        ),
        migrations.AddField(
            model_name='enum',
            name='belong_ct',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='protocal.CustomType'),
        ),
    ]
