-- Generated By Tool Do not Edit
local item = {
    ["12101001"] = {
        ["id"] = 12101001,
        ["name"] = "道具A",
        ["desc"] = "道具A的描述",
        ["res"] = "skdnrkwn",
        ["newres"] = 3894829,
        ["value"] = 100,
        ["logicValue"] = 1,
        ["singleArray1"] = {
            1,
            2,
            3,
        },
        ["singleArray"] = {
            1,
            2,
            3,
        },
        ["doubleArray1"] = {
            {
                1,
                2,
                3,
            },
            {
                4,
                5,
                6,
            },
        },
        ["doubleArray"] = {
            {
                1,
                2,
                3,
            },
            {
                4,
                5,
                6,
            },
        },
    },
    ["12101002"] = {
        ["id"] = 12101002,
        ["name"] = "道具B",
        ["desc"] = "道具B的描述",
        ["res"] = "skdnrkwn",
        ["newres"] = 3894829,
        ["value"] = 100,
        ["logicValue"] = 0,
        ["singleArray1"] = {
            4,
            5,
            6,
        },
        ["singleArray"] = {
            4,
            5,
            6,
        },
        ["doubleArray1"] = {
            {
                7,
                8,
                9,
            },
            {
                10,
                11,
                12,
            },
        },
        ["doubleArray"] = {
            {
                7,
                8,
                9,
            },
            {
                10,
                11,
                12,
            },
        },
    },
    ["12101003"] = {
        ["id"] = 12101003,
        ["name"] = "道具C",
        ["desc"] = "道具C的描述",
        ["res"] = "skdnrkwn",
        ["newres"] = 3894829,
        ["value"] = 100,
        ["logicValue"] = 1,
        ["singleArray1"] = {
            7,
            8,
            9,
        },
        ["singleArray"] = {
            7,
            8,
            9,
        },
        ["doubleArray1"] = {
            {
                13,
                14,
                15,
            },
            {
                16,
                17,
                18,
            },
        },
        ["doubleArray"] = {
            {
                13,
                14,
                15,
            },
            {
                16,
                17,
                18,
            },
        },
    },
}
return item
