-- Generated By Tool Do not Edit
local item = {
    ["12101001"] = {
        ["id"] = 12101001,
        ["name"] = "道具A",
        ["desc"] = "道具A的描述",
        ["res"] = "skdnrkwn",
        ["newres"] = 3894829,
        ["value"] = 100,
        ["logicValue"] = 1,
        ["singleArray1"] = {
            1,
            2,
            3,
        },
        ["singleArray"] = {
            1,
            2,
            3,
        },
        ["doubleArray1"] = {
            {
                1,
                2,
                3,
            },
            {
                4,
                5,
                6,
            },
        },
        ["doubleArray"] = {
            {
                1,
                2,
                3,
            },
            {
                4,
                5,
                6,
            },
        },
    },
    ["12101002"] = {
        ["id"] = 12101002,
        ["name"] = "道具B",
        ["desc"] = "道具B的描述",
        ["res"] = "skdnrkwn",
        ["newres"] = 3894829,
        ["value"] = 100,
        ["logicValue"] = 0,
        ["singleArray1"] = {
            4,
            5,
            6,
        },
        ["singleArray"] = {
            4,
            5,
            6,
        },
        ["doubleArray1"] = {
            {
                7,
                8,
                9,
            },
            {
                10,
                11,
                12,
            },
        },
        ["doubleArray"] = {
            {
                7,
                8,
                9,
            },
            {
                10,
                11,
                12,
            },
        },
    },
    ["12101003"] = {
        ["id"] = 12101003,
        ["name"] = "道具C",
        ["desc"] = "道具C的描述",
        ["res"] = "skdnrkwn",
        ["newres"] = 3894829,
        ["value"] = 100,
        ["logicValue"] = 1,
        ["singleArray1"] = {
            7,
            8,
            9,
        },
        ["singleArray"] = {
            7,
            8,
            9,
        },
        ["doubleArray1"] = {
            {
                13,
                14,
                15,
            },
            {
                16,
                17,
                18,
            },
        },
        ["doubleArray"] = {
            {
                13,
                14,
                15,
            },
            {
                16,
                17,
                18,
            },
        },
    },
    ["12101003"] = {
        ["id"] = 12101003,
        ["name"] = "道具C",
        ["desc"] = "道具C1的描述",
        ["res"] = "skdnrkwn",
        ["newres"] = 3894829,
        ["value"] = 101,
        ["logicValue"] = 1,
        ["singleArray1"] = {
            10,
            11,
            12,
        },
        ["singleArray"] = {
            10,
            11,
            12,
        },
        ["doubleArray1"] = {
            {
                19,
                20,
                21,
            },
            {
                22,
                23,
                24,
            },
        },
        ["doubleArray"] = {
            {
                19,
                20,
                21,
            },
            {
                22,
                23,
                24,
            },
        },
    },
    ["12101003"] = {
        ["id"] = 12101003,
        ["name"] = "道具C",
        ["desc"] = "道具C2的描述",
        ["res"] = "skdnrkwn",
        ["newres"] = 3894829,
        ["value"] = 102,
        ["logicValue"] = 1,
        ["singleArray1"] = {
            10,
            11,
            12,
        },
        ["singleArray"] = {
            10,
            11,
            12,
        },
        ["doubleArray1"] = {
            {
                19,
                20,
                21,
            },
            {
                22,
                23,
                24,
            },
        },
        ["doubleArray"] = {
            {
                19,
                20,
                21,
            },
            {
                22,
                23,
                24,
            },
        },
    },
    ["12101004"] = {
        ["id"] = 12101004,
        ["name"] = "道具D",
        ["desc"] = "道具D的描述",
        ["res"] = "skdnrkwn",
        ["newres"] = 3894829,
        ["value"] = 100,
        ["logicValue"] = 1,
        ["singleArray1"] = {
            13,
            14,
            15,
        },
        ["singleArray"] = {
            13,
            14,
            15,
        },
        ["doubleArray1"] = {
            {
                25,
                26,
                27,
            },
            {
                28,
                29,
                30,
            },
        },
        ["doubleArray"] = {
            {
                25,
                26,
                27,
            },
            {
                28,
                29,
                30,
            },
        },
    },
    ["12101005"] = {
        ["id"] = 12101005,
        ["name"] = "道具E",
        ["desc"] = "道具E的描述",
        ["res"] = "skdnrkwn",
        ["newres"] = 78789,
        ["value"] = 100,
        ["logicValue"] = 0,
        ["singleArray1"] = {
            16,
            17,
            18,
        },
        ["singleArray"] = {
            16,
            17,
            18,
        },
        ["doubleArray1"] = {
            {
                31,
                32,
                33,
            },
            {
                34,
                35,
                36,
            },
        },
        ["doubleArray"] = {
            {
                31,
                32,
                33,
            },
            {
                34,
                35,
                36,
            },
        },
    },
}
return item
