-- Generated By Tool Do not Edit
local script_multlang = {
    ["未知区域"] = {
        ["id"] = "未知区域",
        ["zhcn"] = "未知区域",
    },
    ["未知区域"] = {
        ["id"] = "未知区域",
        ["zhcn"] = "未知区域",
    },
    ["章节未解锁."] = {
        ["id"] = "章节未解锁.",
        ["zhcn"] = "章节未解锁.",
    },
}
return script_multlang
