-- Generated By Tool Do not Edit
local skill_tripleCards_effect = {
    ["items"] = {
        ["1"] = {
            ["id"] = 1,
            ["chainType"] = {
                1,
                1,
                1,
            },
            ["chainTypeUnlockCon"] = 0,
            ["param"] = {
                0,
            },
            ["chainBonus"] = {
                {
                    1,
                    1,
                    200,
                },
                {
                    0,
                    0,
                    0,
                },
                {
                    0,
                    0,
                    0,
                },
            },
        },
        ["2"] = {
            ["id"] = 2,
            ["chainType"] = {
                2,
                2,
                2,
            },
            ["chainTypeUnlockCon"] = 0,
            ["param"] = {
                0,
            },
            ["chainBonus"] = {
                {
                    1,
                    1,
                    200,
                },
                {
                    0,
                    0,
                    0,
                },
                {
                    0,
                    0,
                    0,
                },
            },
        },
        ["3"] = {
            ["id"] = 3,
            ["chainType"] = {
                3,
                3,
                3,
            },
            ["chainTypeUnlockCon"] = 0,
            ["param"] = {
                0,
            },
            ["chainBonus"] = {
                {
                    1,
                    1,
                    200,
                },
                {
                    0,
                    0,
                    0,
                },
                {
                    0,
                    0,
                    0,
                },
            },
        },
        ["4"] = {
            ["id"] = 4,
            ["chainType"] = {
                1,
                1,
                2,
            },
            ["chainTypeUnlockCon"] = 0,
            ["param"] = {
                0,
            },
            ["chainBonus"] = {
                {
                    1,
                    1,
                    200,
                },
                {
                    0,
                    0,
                    0,
                },
                {
                    0,
                    0,
                    0,
                },
            },
        },
        ["5"] = {
            ["id"] = 5,
            ["chainType"] = {
                1,
                1,
                3,
            },
            ["chainTypeUnlockCon"] = 0,
            ["param"] = {
                0,
            },
            ["chainBonus"] = {
                {
                    1,
                    1,
                    200,
                },
                {
                    0,
                    0,
                    0,
                },
                {
                    0,
                    0,
                    0,
                },
            },
        },
        ["6"] = {
            ["id"] = 6,
            ["chainType"] = {
                2,
                2,
                1,
            },
            ["chainTypeUnlockCon"] = 0,
            ["param"] = {
                0,
            },
            ["chainBonus"] = {
                {
                    1,
                    1,
                    200,
                },
                {
                    0,
                    0,
                    0,
                },
                {
                    0,
                    0,
                    0,
                },
            },
        },
        ["7"] = {
            ["id"] = 7,
            ["chainType"] = {
                2,
                2,
                3,
            },
            ["chainTypeUnlockCon"] = 0,
            ["param"] = {
                0,
            },
            ["chainBonus"] = {
                {
                    1,
                    1,
                    200,
                },
                {
                    0,
                    0,
                    0,
                },
                {
                    0,
                    0,
                    0,
                },
            },
        },
        ["8"] = {
            ["id"] = 8,
            ["chainType"] = {
                3,
                3,
                1,
            },
            ["chainTypeUnlockCon"] = 0,
            ["param"] = {
                0,
            },
            ["chainBonus"] = {
                {
                    1,
                    1,
                    200,
                },
                {
                    0,
                    0,
                    0,
                },
                {
                    0,
                    0,
                    0,
                },
            },
        },
        ["9"] = {
            ["id"] = 9,
            ["chainType"] = {
                3,
                3,
                2,
            },
            ["chainTypeUnlockCon"] = 0,
            ["param"] = {
                0,
            },
            ["chainBonus"] = {
                {
                    1,
                    1,
                    200,
                },
                {
                    0,
                    0,
                    0,
                },
                {
                    0,
                    0,
                    0,
                },
            },
        },
        ["10"] = {
            ["id"] = 10,
            ["chainType"] = {
                1,
                2,
                3,
            },
            ["chainTypeUnlockCon"] = 0,
            ["param"] = {
                0,
            },
            ["chainBonus"] = {
                {
                    1,
                    1,
                    200,
                },
                {
                    0,
                    0,
                    0,
                },
                {
                    0,
                    0,
                    0,
                },
            },
        },
    }
}
return skill_tripleCards_effect
