-- Generated By Tool Do not Edit
local skill_tripleCards_effect = {
    ["items"] = {
        ["1"] = {
            ["id"] = 1,
            ["chainType"] = {
                    1,
                    1,
                    1,
            },
            ["chainTypeUnlockCon"] = 0,
            ["param"] = {
                    0,
            },
            ["chainBonus"] = {
                    {
                        1,
                        1,
                        200,
                    },
                    {
                        0,
                        0,
                        0,
                    },
                    {
                        0,
                        0,
                        0,
                    },
            },
        },
    }
}
return skill_tripleCards_effect
