-- Generated By Tool Do not Edit
local system_config = {
    ["items"] = {
        ["5"] = {
            ["maxCharLimit"] = 5,
            ["handCards"] = 4,
            ["cardsDeckMin"] = 10,
            ["cardsDeckMax"] = 10,
            ["staminaMax"] = 10,
            ["staminaRR"] = 1,
            ["cardsDeckCD"] = 0,
            ["playCd"] = 57,
            ["triggerCd"] = 0,
            ["battleTime"] = 99,
            ["battleGroundX"] = 1600,
            ["battleGroundY"] = 600,
            ["battleGroundZ"] = 500,
            ["cameraFarMax"] = 60,
            ["cameraCloseMax"] = 150,
            ["cameraRollSpd"] = 10,
            ["cameraRollTime"] = 10,
        },
    }
}
return system_config
