-- Generated By Tool Do not Edit
local system_beginBattlePosition = {
    ["items"] = {
        ["0"] = {
            ["row"] = 0,
            ["priority"] = 0,
            ["fixPosX"] = 0,
            ["fixPosZUneven"] = 0,
            ["fixPosZEven"] = -25,
        },
        ["1"] = {
            ["row"] = 1,
            ["priority"] = 0,
            ["fixPosX"] = -200,
            ["fixPosZUneven"] = 0,
            ["fixPosZEven"] = -25,
        },
        ["2"] = {
            ["row"] = 2,
            ["priority"] = 0,
            ["fixPosX"] = -400,
            ["fixPosZUneven"] = 0,
            ["fixPosZEven"] = -25,
        },
    }
}
return system_beginBattlePosition
